# ─── Dependencias ───────────────────────────────────────────
FROM node:22-alpine3.19 AS deps
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install

# ─── Builder ────────────────────────────────────────────────
FROM node:22-alpine3.19 AS build
WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .

RUN npm run build
RUN npm prune --omit=dev

# ─── Producción ─────────────────────────────────────────────
FROM node:22-alpine3.19 AS prod
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist

ENV NODE_ENV=production

USER node
EXPOSE 3000

CMD ["node", "dist/main.js"]