# ─── Dependencias ───────────────────────────────────────────
FROM node:22-alpine3.19 AS deps
WORKDIR /usr/src/app


COPY package.json package-lock.json ./
RUN npm install

# ─── Builder ────────────────────────────────────────────────
FROM node:22-alpine3.19 AS build
WORKDIR /usr/src/app
ARG PROD_DATABASE_URL
ENV DATABASE_URL=$PROD_DATABASE_URL

# Imprimir el arg para ver el valor recibido
RUN echo "database_url ::: $PROD_DATABASE_URL";

WORKDIR /usr/src/app

# Copiar de deps, los módulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiar todo el codigo fuente de la aplicación
COPY . .



RUN npx prisma migrate deploy
RUN npx prisma generate
RUN npm run build
RUN npm prune --omit=dev

# ─── Producción ─────────────────────────────────────────────
FROM node:22-alpine3.19 AS prod
WORKDIR /usr/src/app


COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/prisma ./prisma
COPY --from=build /usr/src/app/prisma.config.ts ./
RUN chown -R node:node /usr/src/app

ENV NODE_ENV=production
USER node
EXPOSE 3000

CMD ["node", "dist/main.js"]
